package com.whq.mybatis.customsql.dao;

import com.whq.mybatis.customsql.entity.TaiInasIpsNaNe;
import com.whq.mybatis.customsql.entity.TaiInasIpsNaNeExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaiInasIpsNaNeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    int countByExample(TaiInasIpsNaNeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    int deleteByExample(TaiInasIpsNaNeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal ipsneId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    int insert(TaiInasIpsNaNe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    int insertSelective(TaiInasIpsNaNe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    List<TaiInasIpsNaNe> selectByExample(TaiInasIpsNaNeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    TaiInasIpsNaNe selectByPrimaryKey(BigDecimal ipsneId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") TaiInasIpsNaNe record, @Param("example") TaiInasIpsNaNeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    int updateByExample(@Param("record") TaiInasIpsNaNe record, @Param("example") TaiInasIpsNaNeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    int updateByPrimaryKeySelective(TaiInasIpsNaNe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    int updateByPrimaryKey(TaiInasIpsNaNe record);
}