package com.whq.mybatis.customsql.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TaiInasIpsNaNeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public TaiInasIpsNaNeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIpsneIdIsNull() {
            addCriterion("IPSNE_ID is null");
            return (Criteria) this;
        }

        public Criteria andIpsneIdIsNotNull() {
            addCriterion("IPSNE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andIpsneIdEqualTo(BigDecimal value) {
            addCriterion("IPSNE_ID =", value, "ipsneId");
            return (Criteria) this;
        }

        public Criteria andIpsneIdNotEqualTo(BigDecimal value) {
            addCriterion("IPSNE_ID <>", value, "ipsneId");
            return (Criteria) this;
        }

        public Criteria andIpsneIdGreaterThan(BigDecimal value) {
            addCriterion("IPSNE_ID >", value, "ipsneId");
            return (Criteria) this;
        }

        public Criteria andIpsneIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("IPSNE_ID >=", value, "ipsneId");
            return (Criteria) this;
        }

        public Criteria andIpsneIdLessThan(BigDecimal value) {
            addCriterion("IPSNE_ID <", value, "ipsneId");
            return (Criteria) this;
        }

        public Criteria andIpsneIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("IPSNE_ID <=", value, "ipsneId");
            return (Criteria) this;
        }

        public Criteria andIpsneIdIn(List<BigDecimal> values) {
            addCriterion("IPSNE_ID in", values, "ipsneId");
            return (Criteria) this;
        }

        public Criteria andIpsneIdNotIn(List<BigDecimal> values) {
            addCriterion("IPSNE_ID not in", values, "ipsneId");
            return (Criteria) this;
        }

        public Criteria andIpsneIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("IPSNE_ID between", value1, value2, "ipsneId");
            return (Criteria) this;
        }

        public Criteria andIpsneIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("IPSNE_ID not between", value1, value2, "ipsneId");
            return (Criteria) this;
        }

        public Criteria andNeTypeIsNull() {
            addCriterion("NE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andNeTypeIsNotNull() {
            addCriterion("NE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andNeTypeEqualTo(String value) {
            addCriterion("NE_TYPE =", value, "neType");
            return (Criteria) this;
        }

        public Criteria andNeTypeNotEqualTo(String value) {
            addCriterion("NE_TYPE <>", value, "neType");
            return (Criteria) this;
        }

        public Criteria andNeTypeGreaterThan(String value) {
            addCriterion("NE_TYPE >", value, "neType");
            return (Criteria) this;
        }

        public Criteria andNeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("NE_TYPE >=", value, "neType");
            return (Criteria) this;
        }

        public Criteria andNeTypeLessThan(String value) {
            addCriterion("NE_TYPE <", value, "neType");
            return (Criteria) this;
        }

        public Criteria andNeTypeLessThanOrEqualTo(String value) {
            addCriterion("NE_TYPE <=", value, "neType");
            return (Criteria) this;
        }

        public Criteria andNeTypeLike(String value) {
            addCriterion("NE_TYPE like", value, "neType");
            return (Criteria) this;
        }

        public Criteria andNeTypeNotLike(String value) {
            addCriterion("NE_TYPE not like", value, "neType");
            return (Criteria) this;
        }

        public Criteria andNeTypeIn(List<String> values) {
            addCriterion("NE_TYPE in", values, "neType");
            return (Criteria) this;
        }

        public Criteria andNeTypeNotIn(List<String> values) {
            addCriterion("NE_TYPE not in", values, "neType");
            return (Criteria) this;
        }

        public Criteria andNeTypeBetween(String value1, String value2) {
            addCriterion("NE_TYPE between", value1, value2, "neType");
            return (Criteria) this;
        }

        public Criteria andNeTypeNotBetween(String value1, String value2) {
            addCriterion("NE_TYPE not between", value1, value2, "neType");
            return (Criteria) this;
        }

        public Criteria andNeNameIsNull() {
            addCriterion("NE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andNeNameIsNotNull() {
            addCriterion("NE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNeNameEqualTo(String value) {
            addCriterion("NE_NAME =", value, "neName");
            return (Criteria) this;
        }

        public Criteria andNeNameNotEqualTo(String value) {
            addCriterion("NE_NAME <>", value, "neName");
            return (Criteria) this;
        }

        public Criteria andNeNameGreaterThan(String value) {
            addCriterion("NE_NAME >", value, "neName");
            return (Criteria) this;
        }

        public Criteria andNeNameGreaterThanOrEqualTo(String value) {
            addCriterion("NE_NAME >=", value, "neName");
            return (Criteria) this;
        }

        public Criteria andNeNameLessThan(String value) {
            addCriterion("NE_NAME <", value, "neName");
            return (Criteria) this;
        }

        public Criteria andNeNameLessThanOrEqualTo(String value) {
            addCriterion("NE_NAME <=", value, "neName");
            return (Criteria) this;
        }

        public Criteria andNeNameLike(String value) {
            addCriterion("NE_NAME like", value, "neName");
            return (Criteria) this;
        }

        public Criteria andNeNameNotLike(String value) {
            addCriterion("NE_NAME not like", value, "neName");
            return (Criteria) this;
        }

        public Criteria andNeNameIn(List<String> values) {
            addCriterion("NE_NAME in", values, "neName");
            return (Criteria) this;
        }

        public Criteria andNeNameNotIn(List<String> values) {
            addCriterion("NE_NAME not in", values, "neName");
            return (Criteria) this;
        }

        public Criteria andNeNameBetween(String value1, String value2) {
            addCriterion("NE_NAME between", value1, value2, "neName");
            return (Criteria) this;
        }

        public Criteria andNeNameNotBetween(String value1, String value2) {
            addCriterion("NE_NAME not between", value1, value2, "neName");
            return (Criteria) this;
        }

        public Criteria andNeDescIsNull() {
            addCriterion("NE_DESC is null");
            return (Criteria) this;
        }

        public Criteria andNeDescIsNotNull() {
            addCriterion("NE_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andNeDescEqualTo(String value) {
            addCriterion("NE_DESC =", value, "neDesc");
            return (Criteria) this;
        }

        public Criteria andNeDescNotEqualTo(String value) {
            addCriterion("NE_DESC <>", value, "neDesc");
            return (Criteria) this;
        }

        public Criteria andNeDescGreaterThan(String value) {
            addCriterion("NE_DESC >", value, "neDesc");
            return (Criteria) this;
        }

        public Criteria andNeDescGreaterThanOrEqualTo(String value) {
            addCriterion("NE_DESC >=", value, "neDesc");
            return (Criteria) this;
        }

        public Criteria andNeDescLessThan(String value) {
            addCriterion("NE_DESC <", value, "neDesc");
            return (Criteria) this;
        }

        public Criteria andNeDescLessThanOrEqualTo(String value) {
            addCriterion("NE_DESC <=", value, "neDesc");
            return (Criteria) this;
        }

        public Criteria andNeDescLike(String value) {
            addCriterion("NE_DESC like", value, "neDesc");
            return (Criteria) this;
        }

        public Criteria andNeDescNotLike(String value) {
            addCriterion("NE_DESC not like", value, "neDesc");
            return (Criteria) this;
        }

        public Criteria andNeDescIn(List<String> values) {
            addCriterion("NE_DESC in", values, "neDesc");
            return (Criteria) this;
        }

        public Criteria andNeDescNotIn(List<String> values) {
            addCriterion("NE_DESC not in", values, "neDesc");
            return (Criteria) this;
        }

        public Criteria andNeDescBetween(String value1, String value2) {
            addCriterion("NE_DESC between", value1, value2, "neDesc");
            return (Criteria) this;
        }

        public Criteria andNeDescNotBetween(String value1, String value2) {
            addCriterion("NE_DESC not between", value1, value2, "neDesc");
            return (Criteria) this;
        }

        public Criteria andNeLoginNameIsNull() {
            addCriterion("NE_LOGIN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andNeLoginNameIsNotNull() {
            addCriterion("NE_LOGIN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNeLoginNameEqualTo(String value) {
            addCriterion("NE_LOGIN_NAME =", value, "neLoginName");
            return (Criteria) this;
        }

        public Criteria andNeLoginNameNotEqualTo(String value) {
            addCriterion("NE_LOGIN_NAME <>", value, "neLoginName");
            return (Criteria) this;
        }

        public Criteria andNeLoginNameGreaterThan(String value) {
            addCriterion("NE_LOGIN_NAME >", value, "neLoginName");
            return (Criteria) this;
        }

        public Criteria andNeLoginNameGreaterThanOrEqualTo(String value) {
            addCriterion("NE_LOGIN_NAME >=", value, "neLoginName");
            return (Criteria) this;
        }

        public Criteria andNeLoginNameLessThan(String value) {
            addCriterion("NE_LOGIN_NAME <", value, "neLoginName");
            return (Criteria) this;
        }

        public Criteria andNeLoginNameLessThanOrEqualTo(String value) {
            addCriterion("NE_LOGIN_NAME <=", value, "neLoginName");
            return (Criteria) this;
        }

        public Criteria andNeLoginNameLike(String value) {
            addCriterion("NE_LOGIN_NAME like", value, "neLoginName");
            return (Criteria) this;
        }

        public Criteria andNeLoginNameNotLike(String value) {
            addCriterion("NE_LOGIN_NAME not like", value, "neLoginName");
            return (Criteria) this;
        }

        public Criteria andNeLoginNameIn(List<String> values) {
            addCriterion("NE_LOGIN_NAME in", values, "neLoginName");
            return (Criteria) this;
        }

        public Criteria andNeLoginNameNotIn(List<String> values) {
            addCriterion("NE_LOGIN_NAME not in", values, "neLoginName");
            return (Criteria) this;
        }

        public Criteria andNeLoginNameBetween(String value1, String value2) {
            addCriterion("NE_LOGIN_NAME between", value1, value2, "neLoginName");
            return (Criteria) this;
        }

        public Criteria andNeLoginNameNotBetween(String value1, String value2) {
            addCriterion("NE_LOGIN_NAME not between", value1, value2, "neLoginName");
            return (Criteria) this;
        }

        public Criteria andNeLoginPwdIsNull() {
            addCriterion("NE_LOGIN_PWD is null");
            return (Criteria) this;
        }

        public Criteria andNeLoginPwdIsNotNull() {
            addCriterion("NE_LOGIN_PWD is not null");
            return (Criteria) this;
        }

        public Criteria andNeLoginPwdEqualTo(String value) {
            addCriterion("NE_LOGIN_PWD =", value, "neLoginPwd");
            return (Criteria) this;
        }

        public Criteria andNeLoginPwdNotEqualTo(String value) {
            addCriterion("NE_LOGIN_PWD <>", value, "neLoginPwd");
            return (Criteria) this;
        }

        public Criteria andNeLoginPwdGreaterThan(String value) {
            addCriterion("NE_LOGIN_PWD >", value, "neLoginPwd");
            return (Criteria) this;
        }

        public Criteria andNeLoginPwdGreaterThanOrEqualTo(String value) {
            addCriterion("NE_LOGIN_PWD >=", value, "neLoginPwd");
            return (Criteria) this;
        }

        public Criteria andNeLoginPwdLessThan(String value) {
            addCriterion("NE_LOGIN_PWD <", value, "neLoginPwd");
            return (Criteria) this;
        }

        public Criteria andNeLoginPwdLessThanOrEqualTo(String value) {
            addCriterion("NE_LOGIN_PWD <=", value, "neLoginPwd");
            return (Criteria) this;
        }

        public Criteria andNeLoginPwdLike(String value) {
            addCriterion("NE_LOGIN_PWD like", value, "neLoginPwd");
            return (Criteria) this;
        }

        public Criteria andNeLoginPwdNotLike(String value) {
            addCriterion("NE_LOGIN_PWD not like", value, "neLoginPwd");
            return (Criteria) this;
        }

        public Criteria andNeLoginPwdIn(List<String> values) {
            addCriterion("NE_LOGIN_PWD in", values, "neLoginPwd");
            return (Criteria) this;
        }

        public Criteria andNeLoginPwdNotIn(List<String> values) {
            addCriterion("NE_LOGIN_PWD not in", values, "neLoginPwd");
            return (Criteria) this;
        }

        public Criteria andNeLoginPwdBetween(String value1, String value2) {
            addCriterion("NE_LOGIN_PWD between", value1, value2, "neLoginPwd");
            return (Criteria) this;
        }

        public Criteria andNeLoginPwdNotBetween(String value1, String value2) {
            addCriterion("NE_LOGIN_PWD not between", value1, value2, "neLoginPwd");
            return (Criteria) this;
        }

        public Criteria andNeAliasIsNull() {
            addCriterion("NE_ALIAS is null");
            return (Criteria) this;
        }

        public Criteria andNeAliasIsNotNull() {
            addCriterion("NE_ALIAS is not null");
            return (Criteria) this;
        }

        public Criteria andNeAliasEqualTo(String value) {
            addCriterion("NE_ALIAS =", value, "neAlias");
            return (Criteria) this;
        }

        public Criteria andNeAliasNotEqualTo(String value) {
            addCriterion("NE_ALIAS <>", value, "neAlias");
            return (Criteria) this;
        }

        public Criteria andNeAliasGreaterThan(String value) {
            addCriterion("NE_ALIAS >", value, "neAlias");
            return (Criteria) this;
        }

        public Criteria andNeAliasGreaterThanOrEqualTo(String value) {
            addCriterion("NE_ALIAS >=", value, "neAlias");
            return (Criteria) this;
        }

        public Criteria andNeAliasLessThan(String value) {
            addCriterion("NE_ALIAS <", value, "neAlias");
            return (Criteria) this;
        }

        public Criteria andNeAliasLessThanOrEqualTo(String value) {
            addCriterion("NE_ALIAS <=", value, "neAlias");
            return (Criteria) this;
        }

        public Criteria andNeAliasLike(String value) {
            addCriterion("NE_ALIAS like", value, "neAlias");
            return (Criteria) this;
        }

        public Criteria andNeAliasNotLike(String value) {
            addCriterion("NE_ALIAS not like", value, "neAlias");
            return (Criteria) this;
        }

        public Criteria andNeAliasIn(List<String> values) {
            addCriterion("NE_ALIAS in", values, "neAlias");
            return (Criteria) this;
        }

        public Criteria andNeAliasNotIn(List<String> values) {
            addCriterion("NE_ALIAS not in", values, "neAlias");
            return (Criteria) this;
        }

        public Criteria andNeAliasBetween(String value1, String value2) {
            addCriterion("NE_ALIAS between", value1, value2, "neAlias");
            return (Criteria) this;
        }

        public Criteria andNeAliasNotBetween(String value1, String value2) {
            addCriterion("NE_ALIAS not between", value1, value2, "neAlias");
            return (Criteria) this;
        }

        public Criteria andNeIpIsNull() {
            addCriterion("NE_IP is null");
            return (Criteria) this;
        }

        public Criteria andNeIpIsNotNull() {
            addCriterion("NE_IP is not null");
            return (Criteria) this;
        }

        public Criteria andNeIpEqualTo(String value) {
            addCriterion("NE_IP =", value, "neIp");
            return (Criteria) this;
        }

        public Criteria andNeIpNotEqualTo(String value) {
            addCriterion("NE_IP <>", value, "neIp");
            return (Criteria) this;
        }

        public Criteria andNeIpGreaterThan(String value) {
            addCriterion("NE_IP >", value, "neIp");
            return (Criteria) this;
        }

        public Criteria andNeIpGreaterThanOrEqualTo(String value) {
            addCriterion("NE_IP >=", value, "neIp");
            return (Criteria) this;
        }

        public Criteria andNeIpLessThan(String value) {
            addCriterion("NE_IP <", value, "neIp");
            return (Criteria) this;
        }

        public Criteria andNeIpLessThanOrEqualTo(String value) {
            addCriterion("NE_IP <=", value, "neIp");
            return (Criteria) this;
        }

        public Criteria andNeIpLike(String value) {
            addCriterion("NE_IP like", value, "neIp");
            return (Criteria) this;
        }

        public Criteria andNeIpNotLike(String value) {
            addCriterion("NE_IP not like", value, "neIp");
            return (Criteria) this;
        }

        public Criteria andNeIpIn(List<String> values) {
            addCriterion("NE_IP in", values, "neIp");
            return (Criteria) this;
        }

        public Criteria andNeIpNotIn(List<String> values) {
            addCriterion("NE_IP not in", values, "neIp");
            return (Criteria) this;
        }

        public Criteria andNeIpBetween(String value1, String value2) {
            addCriterion("NE_IP between", value1, value2, "neIp");
            return (Criteria) this;
        }

        public Criteria andNeIpNotBetween(String value1, String value2) {
            addCriterion("NE_IP not between", value1, value2, "neIp");
            return (Criteria) this;
        }

        public Criteria andNePortIsNull() {
            addCriterion("NE_PORT is null");
            return (Criteria) this;
        }

        public Criteria andNePortIsNotNull() {
            addCriterion("NE_PORT is not null");
            return (Criteria) this;
        }

        public Criteria andNePortEqualTo(String value) {
            addCriterion("NE_PORT =", value, "nePort");
            return (Criteria) this;
        }

        public Criteria andNePortNotEqualTo(String value) {
            addCriterion("NE_PORT <>", value, "nePort");
            return (Criteria) this;
        }

        public Criteria andNePortGreaterThan(String value) {
            addCriterion("NE_PORT >", value, "nePort");
            return (Criteria) this;
        }

        public Criteria andNePortGreaterThanOrEqualTo(String value) {
            addCriterion("NE_PORT >=", value, "nePort");
            return (Criteria) this;
        }

        public Criteria andNePortLessThan(String value) {
            addCriterion("NE_PORT <", value, "nePort");
            return (Criteria) this;
        }

        public Criteria andNePortLessThanOrEqualTo(String value) {
            addCriterion("NE_PORT <=", value, "nePort");
            return (Criteria) this;
        }

        public Criteria andNePortLike(String value) {
            addCriterion("NE_PORT like", value, "nePort");
            return (Criteria) this;
        }

        public Criteria andNePortNotLike(String value) {
            addCriterion("NE_PORT not like", value, "nePort");
            return (Criteria) this;
        }

        public Criteria andNePortIn(List<String> values) {
            addCriterion("NE_PORT in", values, "nePort");
            return (Criteria) this;
        }

        public Criteria andNePortNotIn(List<String> values) {
            addCriterion("NE_PORT not in", values, "nePort");
            return (Criteria) this;
        }

        public Criteria andNePortBetween(String value1, String value2) {
            addCriterion("NE_PORT between", value1, value2, "nePort");
            return (Criteria) this;
        }

        public Criteria andNePortNotBetween(String value1, String value2) {
            addCriterion("NE_PORT not between", value1, value2, "nePort");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 21 17:02:54 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TAI_INAS_IPS_NA_NE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}