package com.whq.mybatis.customsql.entity;

import java.math.BigDecimal;

public class TaiInasIpsNaNe {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAI_INAS_IPS_NA_NE.IPSNE_ID
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    private BigDecimal ipsneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAI_INAS_IPS_NA_NE.NE_TYPE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    private String neType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAI_INAS_IPS_NA_NE.NE_NAME
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    private String neName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAI_INAS_IPS_NA_NE.NE_DESC
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    private String neDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAI_INAS_IPS_NA_NE.NE_LOGIN_NAME
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    private String neLoginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAI_INAS_IPS_NA_NE.NE_LOGIN_PWD
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    private String neLoginPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAI_INAS_IPS_NA_NE.NE_ALIAS
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    private String neAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAI_INAS_IPS_NA_NE.NE_IP
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    private String neIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAI_INAS_IPS_NA_NE.NE_PORT
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    private String nePort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAI_INAS_IPS_NA_NE.IPSNE_ID
     *
     * @return the value of TAI_INAS_IPS_NA_NE.IPSNE_ID
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public BigDecimal getIpsneId() {
        return ipsneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAI_INAS_IPS_NA_NE.IPSNE_ID
     *
     * @param ipsneId the value for TAI_INAS_IPS_NA_NE.IPSNE_ID
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public void setIpsneId(BigDecimal ipsneId) {
        this.ipsneId = ipsneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAI_INAS_IPS_NA_NE.NE_TYPE
     *
     * @return the value of TAI_INAS_IPS_NA_NE.NE_TYPE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public String getNeType() {
        return neType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAI_INAS_IPS_NA_NE.NE_TYPE
     *
     * @param neType the value for TAI_INAS_IPS_NA_NE.NE_TYPE
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public void setNeType(String neType) {
        this.neType = neType == null ? null : neType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAI_INAS_IPS_NA_NE.NE_NAME
     *
     * @return the value of TAI_INAS_IPS_NA_NE.NE_NAME
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public String getNeName() {
        return neName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAI_INAS_IPS_NA_NE.NE_NAME
     *
     * @param neName the value for TAI_INAS_IPS_NA_NE.NE_NAME
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public void setNeName(String neName) {
        this.neName = neName == null ? null : neName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAI_INAS_IPS_NA_NE.NE_DESC
     *
     * @return the value of TAI_INAS_IPS_NA_NE.NE_DESC
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public String getNeDesc() {
        return neDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAI_INAS_IPS_NA_NE.NE_DESC
     *
     * @param neDesc the value for TAI_INAS_IPS_NA_NE.NE_DESC
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public void setNeDesc(String neDesc) {
        this.neDesc = neDesc == null ? null : neDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAI_INAS_IPS_NA_NE.NE_LOGIN_NAME
     *
     * @return the value of TAI_INAS_IPS_NA_NE.NE_LOGIN_NAME
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public String getNeLoginName() {
        return neLoginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAI_INAS_IPS_NA_NE.NE_LOGIN_NAME
     *
     * @param neLoginName the value for TAI_INAS_IPS_NA_NE.NE_LOGIN_NAME
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public void setNeLoginName(String neLoginName) {
        this.neLoginName = neLoginName == null ? null : neLoginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAI_INAS_IPS_NA_NE.NE_LOGIN_PWD
     *
     * @return the value of TAI_INAS_IPS_NA_NE.NE_LOGIN_PWD
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public String getNeLoginPwd() {
        return neLoginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAI_INAS_IPS_NA_NE.NE_LOGIN_PWD
     *
     * @param neLoginPwd the value for TAI_INAS_IPS_NA_NE.NE_LOGIN_PWD
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public void setNeLoginPwd(String neLoginPwd) {
        this.neLoginPwd = neLoginPwd == null ? null : neLoginPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAI_INAS_IPS_NA_NE.NE_ALIAS
     *
     * @return the value of TAI_INAS_IPS_NA_NE.NE_ALIAS
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public String getNeAlias() {
        return neAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAI_INAS_IPS_NA_NE.NE_ALIAS
     *
     * @param neAlias the value for TAI_INAS_IPS_NA_NE.NE_ALIAS
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public void setNeAlias(String neAlias) {
        this.neAlias = neAlias == null ? null : neAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAI_INAS_IPS_NA_NE.NE_IP
     *
     * @return the value of TAI_INAS_IPS_NA_NE.NE_IP
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public String getNeIp() {
        return neIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAI_INAS_IPS_NA_NE.NE_IP
     *
     * @param neIp the value for TAI_INAS_IPS_NA_NE.NE_IP
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public void setNeIp(String neIp) {
        this.neIp = neIp == null ? null : neIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAI_INAS_IPS_NA_NE.NE_PORT
     *
     * @return the value of TAI_INAS_IPS_NA_NE.NE_PORT
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public String getNePort() {
        return nePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAI_INAS_IPS_NA_NE.NE_PORT
     *
     * @param nePort the value for TAI_INAS_IPS_NA_NE.NE_PORT
     *
     * @mbggenerated Thu Dec 21 17:02:54 CST 2017
     */
    public void setNePort(String nePort) {
        this.nePort = nePort == null ? null : nePort.trim();
    }
}